version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
      dev-dependencies:
        patterns:
          - "@types/*"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
