repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/oxc-project/mirrors-oxlint
    rev: v1.60.0
    hooks:
      - id: oxlint
        verbose: true
