allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  "@tsparticles/engine": true
  core-js: true
  esbuild: true
  puppeteer: false
  workerd: true
overrides:
  esbuild: ">=0.28.1"
  serialize-javascript: ">=7.0.3"
