name: Clean

on:
  schedule:
    - cron: "0 0 1 * *"

permissions:
  actions: write
  contents: write

jobs:
  workflow-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 6
