# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Tests
permissions:
  contents: read

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4.2.3
        with:
          path: |
            .astro
            node_modules
          key: build
      - name: Use pnpm Version 10.x.x
        uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm run test
      - name: Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: pnpm run build && pnpm run preview --host
          browser: chrome
